abstract Constants = ConstantBase ** {

-- generated by MkConstants.hs

fun Dk_Zero : Const ;
fun Dk_Succ : Fun ;
fun Dk_eqZero : Label ;
fun Dk_eqSucc : Label ;
fun Dk_eqSumZero : Label ;
fun Dk_eqSumSucc : Label ;
fun Dk_gcdLt : Label ;
fun Dk_evenOdd : Label ;
fun Dk_primeOdd : Label ;
}
