concrete UserConstantsSwe of UserConstants = BaseConstantsSwe **

-- generated by MkConstants.hs

open
  UtilitiesSwe,
  SyntaxSwe,
  ParadigmsSwe,
  SymbolicSwe,
  Formal

in {

lin Dk_same_parity = mkRel "paritetslik" "med" ; ----

}
