concrete UserConstantsEng of UserConstants = BaseConstantsEng **

-- generated by MkConstants.hs

open
  SyntaxEng,
  ParadigmsEng,
  SymbolicEng,
  Formal

in {

lin Dk_same_parity = mkRel "equal in parity" "with" ; ----

}
