concrete UserConstantsFre of UserConstants = BaseConstantsFre **

-- generated by MkConstants.hs

open
  SyntaxFre,
  ParadigmsFre,
  SymbolicFre,
  Formal

in {

lin Dk_same_parity = mkRel "paritégal" "avec" ; ---- 

}
