all: pgf

.PHONY : all pgf

pgf:
	gf --make -output-format=haskell -haskell=lexical -lexical=QN,Variable,Kind,Fun1,Fun2 --haskell=gadt MathTextEng.gf MathTextFin.gf MathTextFre.gf MathTextGer.gf MathTextIta.gf MathTextPor.gf MathTextSwe.gf MathTextLean.gf
