abstract Constants = ConstantBase ** {

-- generated by MkConstants.hs

fun Dk_Type : Noun ;
fun Dk_Nat : Noun ;
fun Dk_Set : Noun ;
fun Dk_Even : Adj ;
fun Dk_Odd : Adj ;
fun Dk_Prime : Adj ;
fun Dk_Zero : Name ;
fun Dk_Div : Rel ;
fun Dk_Eq : Rel ;
fun Dk_Lt : Rel ;
fun Dk_Gt : Rel ;
fun Dk_Succ : Fun ;
fun Dk_sum : Fun ;
fun Dk_prod : Fun ;
fun Dk_gcd : Fun ;
fun Dk_eqZerp : Label ;
fun Dk_eqSucc : Label ;
}
