all:
	first_Eng
	added_Ger
	added_Fre
	added_Fin

first_Eng:
	./build_lexicon.py -first en Eng 1 2 3 4 5 6

added_Ger:
	./build_lexicon.py -added de Ger 1 2 3 4 5 7

added_Fre:
	./build_lexicon.py -added fr Fre 1 2 3 4 5 7

added_Fin:
	./build_lexicon.py -added fi Fin 1 2 3 4 5 7

